spring:
  application:
    name: idempotency-gateway

  datasource:
    url: jdbc:sqlite:idempotency.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    operationsSorter: method

app:
  idempotency:
    ttl-hours: 36